title: 新井『数学基礎論』勉強会資料
description: 新井敏康『数学基礎論 増補版』(東大出版会)の勉強会での板書・配付資料・ホワイトボードなど。レジュメとしてまとめることをしていないので，参加者の復習用という感じ。
show_downloads: true
google_analytics:

author:
  name: Munenori IIDA
  email: flashingwind@gmail.com

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-gallery-generator

gallery:
  dir: .                   # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: "Notes"           # Title for gallery index page
  title_prefix: "Notes: "  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  
  galleries:
    notes:
